# Generated by Django on 2026-04-09
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='pedidos', to='pedidos.cliente'),
        ),
    ]
